baseURL = "https://www.technikaya.com/" #This will be the URL of your Website
languageCode = "en-us" #Your Website Language (Used for SEO)
title = "Technikaya" #Your Website Name
paginate = 6 #Number of Post on Homepage
googleAnalytics = "UA-1920" #Google Analytics Tracking ID

#Don't Change These Things
[related]
  includeNewer = true
  threshold = 80
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[[related.indices]]
  name = "date"
  weight = 10

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

#Don't Change These Things

[permalinks]
  categories = "/:title/"
  tags = "/:title/"

[params]
    logo = "/images/logo.png" #Logo of your Website (Put Image in dir /static/images)
    description = "Best Gaming Reviews & News" #SEO Discription of your Website
    excrept = "At Technikaya, you will get all of the latest technology news and reviews, while for accumulated technology experience, we also cover tech guides." #SEO Exprect of Your Website
    image = "/images/site_banner.png" #Business Cover (1920x1080) Used in SEO
    icon = "/images/favicon.png" #Favicon

    siteAuthor = "Eric Cowell" #Your Name
    AuthorImage = "/images/author.png" #Your Profile Picure
    AuthorBio = "ove to play AAA Games" #Your Author BIO
    contactMail = "contact@thewebsite.com"

    googleSiteVerify = "code1" #Google Search Console Verification
    BingWebmaster = "code2" #Bing Verification
    PinterestVerify = "code3" #Pinterest Verification

      ##OpenGraph Meta Start
    FacebookPublisher = "https://facebook.com/" #Open Graph Publisher Tag (Facebook)
    FacebookAuthor = "https://facebook.com/" #Open Graph Author Tag (Facebook)
    TwitterPublisher = "@twitter" #Open Graph Publisher Tag (Twitter) Just Put Username
    TwitterAuthor = "@twitter"  #Open Graph Author Tag (Twitter) Just Put Username
      ##OpenGraph Meta END

      ##Social Media Profiles Start
      SocialFB = "https://facebook.com/technikaya"
      SocialTwitter = "https://twitter.com/technikaya"
      SocialYouTube = "https://youtube.com/channel/UCydTdtjJ1V2p--2bOXx1XGg"
      SocialTumblr = "https://technikaya.tumblr.com/"
      SocialLinkedin = "www.linkedin.com/in/technikaya-reviews-423544203"
      SocialPinterest = "https://pinterest.com/Technikaya_"
      ##Social Media Profiles END

[taxonomies]
  category = "categories" #Taxonomy Category
  tag = "tags" #Taxonomy Tags
  #You can Add More Taxnomies by Singular = "Prular"

  #Header Menu Start (Order By Weight)
[[menu.mainmenu]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.mainmenu]]
  name = "GAMING BUILDS"
  url = "/gaming-builds/"
  weight = 2

[[menu.mainmenu]]
  name = "Reviews"
  url = "/reviews/"
  weight = 3

[[menu.mainmenu]]
  name = "Information"
  url = "/information/"
  weight = 4

  #Header Menu END
  #Footer Menu Start (Order By Weight)

[[menu.footermenu]]
  name = "HOME"
  url = "/"
  weight = "1"
  
[[menu.footermenu]]
  name = "About Us"
  url = "/about/"
  weight = "2"

[[menu.footermenu]]
  name = "Contact Us"
  url = "/contact/"
  weight = "3"

[[menu.footermenu]]
  name = "Affiliate Disclosure"
  url = "/affiliate-disclosure/"
  weight = "4"

  #Footer Menu END
