backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:

#Posts Collection
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - {label: "Title", name: "title" , widget: "string", required: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "SEO Title", name: "SEOTitle", widget: "string", required: true}
      - {label: "SEO Discription", name: "excrept", widget: "text", required: true}
      - {label: "Slug", name: "url", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Modify Date", name: "updateDate", widget: "datetime"}
      - {label: "Featured Image (Size 1200x680)", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "relation", collection: "tags", searchFields: ["name"], valueField: "name", displayFields: ["name"], multiple: true}
      - {label: "Categories", name: "categories", widget: "relation", collection: "categories", searchFields: ["name"], valueField: "name", displayFields: ["name"], multiple: true}
      - {label: "Staff Pick P.Name", name: "pickName", widget: "string"}
      - {label: "Staff Pick P.Image", name: "pickImg", widget: "image"}
      - {label: "Staff Pick P.Link", name: "pickLink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

#Categories Collection
  - name: categories
    label: Categories
    folder: content/categories/
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields: 
      - {name: name, label: Name}
      - {name: excrept, label: SEO Discription}
      - {name: url, label: Slug}

#Tags Collection
  - name: tags
    label: Tags
    folder: content/tags/
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields: 
      - {name: name, label: Name}
      - {name: excrept, label: SEO Discription}
      - {name: url, label: Slug}

#Pages Collection
